# a=int(input(":"))
# b=int(input(":"))
# try:
#     print(a,b)
#     print(a,"/",b,"=",a/b)
#
# except:
#     print("Exception occured")

#the 'try' block always work in every cases
#but the 'except' block work only when an error occures in the try block

#............................................................................................................................

# lst=[1,2,3]
# n=int(input(":"))
# try:
#     print(lst[n])
# except:
#     print("Index out of range")
#......................................................................................................................

#finally block
#try:
#exception:
#finally


# lst=[1,2,3]
# n=int(input(":"))
# try:
#     print(lst[n])
# except:
#     print("Index out of range")
#
# finally:
#     print("Inside the finally block")


#..................................
#finally block always work..after the each try and exception block if we want to excute a block of code we add the code here
#just to code execute